#!/usr/bin/env python3
"""Regenerate docs/NEEDS_REVIEW.md from recipes/**/recipe.json (low-confidence list, untitled list, rescan tips)."""
import glob, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
recs, batches = [], {}
for bj in glob.glob(os.path.join(ROOT, "recipes", "batch-*", "batch.json")):
    b = json.load(open(bj, encoding="utf-8")); batches[b["batch"]] = b.get("title") or ""
for p in sorted(glob.glob(os.path.join(ROOT, "recipes", "batch-*", "b*-r*", "recipe.json"))):
    recs.append(json.load(open(p, encoding="utf-8")))
cnt = {k: sum(r["confidence"] == k for r in recs) for k in ("high", "medium", "low")}
flagged = sum(r["needs_human_verification"] for r in recs)
out = ["# Needs review and rescan", "",
       f"Generated by tools/needs_review.py from the recipe JSON files. {len(recs)} recipes in {len(batches)} batch folders "
       "(see docs/BATCH_NUMBERING.md: Batch 4 is intentionally empty, batch 99 = loose scans).",
       f"Confidence: high {cnt['high']}, medium {cnt['medium']}, low {cnt['low']}. Flagged needs_human_verification: {flagged}.", "",
       "## Low-confidence recipes (rescan, or a human who knows Ilana's handwriting, recommended)", "",
       "| Recipe | Batch | Title | Scan files | Medium |", "|---|---|---|---|---|"]
for r in recs:
    if r["confidence"] == "low":
        files = ", ".join(f["original_path"] for f in r["raw_files"])
        out.append(f"| {r['id']} | {r['batch']} {batches.get(r['batch'], '')} | {r['title'] or '(no title read)'} | {files} | {r['medium']} |")
out += ["", "## Recipes with no title read", "", ", ".join(r["id"] for r in recs if not r["title"]), "",
        "## Rescanning tips", "",
        "Scan handwritten cards flat at 300-600 dpi, one side at a time, with the whole card inside the frame, and put a dark sheet "
        "behind thin memo paper to cut show-through from the other side. Scan both sides of every double-sided card.", ""]
open(os.path.join(ROOT, "docs", "NEEDS_REVIEW.md"), "w", encoding="utf-8").write("\n".join(out))
print("docs/NEEDS_REVIEW.md written:", cnt)
